/**
 * Markdown report formatting.
 * @module report/markdown
 */

import type { CompareReport } from '../schemas/index.js'

/**
 * Formats a comparison report as REPORT.md markdown.
 */
export function formatReportMd(report: CompareReport): string {
  const lines: string[] = []

  lines.push('# Scout Comparison Report')
  lines.push('')
  lines.push(`**Generated:** ${report.timestamp}`)
  lines.push(`**Run ID:** ${report.runId}`)
  lines.push('')

  // Summary section
  lines.push('## Summary')
  lines.push('')
  lines.push('| Metric | Value |')
  lines.push('|--------|-------|')
  lines.push(`| Total Discovered | ${report.summary.totalDiscovered} |`)
  lines.push(`| Cloned | ${report.summary.cloned} |`)
  lines.push(`| Validated with Matches | ${report.summary.validated} |`)
  if (report.summary.topRecommendation) {
    lines.push(`| **Top Recommendation** | **${report.summary.topRecommendation}** |`)
  }
  lines.push('')

  // Source project section
  lines.push('## Source Project')
  lines.push('')
  lines.push(`- **Root:** \`${report.sourceProject.root}\``)
  if (report.sourceProject.commit) {
    lines.push(`- **Commit:** \`${report.sourceProject.commit}\``)
  }
  if (report.sourceProject.targetKinds.length > 0) {
    lines.push(`- **Target Kinds:** ${report.sourceProject.targetKinds.join(', ')}`)
  }
  lines.push('')

  // Ranked candidates
  lines.push('## Ranked Candidates')
  lines.push('')

  if (report.candidates.length === 0) {
    lines.push('*No candidates found matching the target patterns.*')
    lines.push('')
  } else {
    for (const [i, c] of report.candidates.entries()) {
      const rank = i + 1

      lines.push(`### ${rank}. ${c.repo}`)
      lines.push('')

      // Scores
      const tier1Pct = Math.round(c.tier1Score * 100)
      const tier2Pct = Math.round(c.tier2Score * 100)
      const modernityPct = Math.round(c.modernityScore * 100)

      lines.push('| Metric | Score |')
      lines.push('|--------|-------|')
      lines.push(`| Tier1 (Discovery) | ${tier1Pct}% |`)
      lines.push(`| Tier2 (Validation) | ${tier2Pct}% |`)
      lines.push(`| Modernity | ${modernityPct}% |`)
      lines.push('')

      // Matched kinds
      if (c.matchedKinds.length > 0) {
        lines.push(`**Matched Components:** ${c.matchedKinds.join(', ')}`)
        lines.push('')
      }

      // License
      if (c.license) {
        lines.push(`**License:** ${c.license}`)
        lines.push('')
      }

      // Entrypoints
      if (c.topEntrypoints.length > 0) {
        lines.push('**Key Entrypoints:**')
        for (const ep of c.topEntrypoints) {
          lines.push(`- \`${ep}\``)
        }
        lines.push('')
      }

      // Link
      lines.push(`**GitHub:** [${c.repo}](https://github.com/${c.repo})`)
      lines.push('')
      lines.push('---')
      lines.push('')
    }
  }

  // Score breakdown explanation
  lines.push('## Scoring Methodology')
  lines.push('')
  lines.push('### Tier1 Score (Discovery)')
  lines.push('Based on:')
  lines.push('- **Recency** (55%): How recently the repo was updated')
  lines.push('- **Activity** (25%): Stars and forks (log-scaled)')
  lines.push('- **Lane Hits** (20%): How many search strategies matched')
  lines.push('')
  lines.push('### Tier2 Score (Validation)')
  lines.push('Tier1 score plus:')
  lines.push('- **Structural Match** (35%): Component kinds detected')
  lines.push('- **Modernity** (20%): Modern tooling practices')
  lines.push('')

  // Footer
  lines.push('---')
  lines.push('')
  lines.push('*Generated by [Scout CLI](https://github.com/4meta5/scout)*')
  lines.push('')

  return lines.join('\n')
}

/**
 * Formats a condensed summary for terminal output.
 */
export function formatTerminalSummary(report: CompareReport): string {
  const lines: string[] = []

  lines.push('┌─────────────────────────────────────────────┐')
  lines.push('│           SCOUT COMPARISON REPORT           │')
  lines.push('└─────────────────────────────────────────────┘')
  lines.push('')
  lines.push(`Discovery: ${report.summary.totalDiscovered} → Clone: ${report.summary.cloned} → Validated: ${report.summary.validated}`)
  lines.push('')

  if (report.summary.topRecommendation) {
    lines.push(`🏆 Top Recommendation: ${report.summary.topRecommendation}`)
    lines.push('')
  }

  lines.push('Rankings:')
  for (const [i, c] of report.candidates.slice(0, 5).entries()) {
    const tier2Pct = Math.round(c.tier2Score * 100)
    const kinds = c.matchedKinds.join(', ') || 'library'
    lines.push(`  ${i + 1}. ${c.repo} (${tier2Pct}%) - ${kinds}`)
  }

  return lines.join('\n')
}
